// import { getAllCategories, getAllCategoryByID, deleteCategoryByID ,postCategory, editCategorybyId} from "./httprequests.js";

// let list = document.querySelector("#categories");
// let detail = document.querySelector("#detail")
// //use categories
// getAllCategories().then(data => {
//     data.forEach(category => {
//         list.innerHTML += `<li>${category.name}</li>`
//     });

// })

// // //use category by ID


// // getAllCategoryByID(3).then(data => {
// //     if(data.id){
// //     detail.textContent = `${data.name} ,desc: ${data.description}`;}
// //     else{
// //         detail.textContent=`category not found`;
// //     }
// // })
// // //use deletecategory by ID
// // deleteCategoryByID(2);

// // //use Postcategory by ID

// // postCategory({name:'Baba kazimovich from Yasamal',description:'ses123'});


// ///use edit category
// // editCategorybyId(1,{
// //     name:'salam',
// //     description:'salam123'
// // }) 